### ISSUE TITLE
fatal error: es8311.h

### ISSUE THREAD

**Issue by dony71** [mulcmu/home-skainet#7]
I try to compile using ESP-IDF v4.4.2 and get this error below
es8311.h is missing. Please help
 
C:/Project/esp-skainet/examples/home-skainet/main/main.c:27:10: fatal error: es8311.h: No such file or directory  #include "es8311.h"
